// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.FibonacciGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("sequence")]
        public long[] Sequence { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("start_from")]
        public long StartFrom { get; set; }

        [JsonProperty("first_value")]
        public long FirstValue { get; set; }

        [JsonProperty("last_value")]
        public long LastValue { get; set; }

        [JsonProperty("sum")]
        public long Sum { get; set; }

        [JsonProperty("ratios")]
        public double[] Ratios { get; set; }

        [JsonProperty("golden_ratio_approximation")]
        public double GoldenRatioApproximation { get; set; }
    }
}
